[package]
name = "gateway-mfr"
version = "0.1.0"
authors = ["Marc Nijdam <marc@helium.com>"]
edition = "2018"
license = "Apache-2.0"

[workspace]
members = ["ecc608-linux-rs"]

[[bin]]
name = "gateway_mfr"
path = "src/main.rs"
doc = false

[dependencies]
structopt = "0"
anyhow = "1"
semver = "0"
prettytable-rs = "0"
ecc608-linux = {path = "ecc608-linux-rs"}
helium-crypto = {git = "https://github.com/helium/helium-crypto-rs", tag="v0.0.8"}

[patch.crates-io]
elliptic-curve = { git = "https://github.com/helium/traits.git", branch = "rg/compact" }
